# Generated by Django 4.0.3 on 2022-08-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('co_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_id', models.TextField()),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('position', models.TextField()),
                ('reward', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('technique', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(unique=True)),
                ('apply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.notification')),
            ],
        ),
    ]
