# Generated by Django 4.1 on 2022-08-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Another",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="anothers",
            field=models.ManyToManyField(blank=True, to="recruit.another"),
        ),
    ]
