# Generated by Django 4.1 on 2022-08-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_another_notification_anothers"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="anothers",),
        migrations.DeleteModel(name="Another",),
    ]
